# Kod Boyutu Optimizasyonları (Flash Taşmasını Önler)
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_OPENTHREAD_DIAG=n
CONFIG_OPENTHREAD_LOG_LEVEL_DYNAMIC=n
CONFIG_OPENTHREAD_LOG_LEVEL=0

# Donanım ve Sürücü Ayarları
CONFIG_GPIO=y
CONFIG_NETWORKING=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_OPENTHREAD=y
CONFIG_OPENTHREAD_COPROCESSOR_RCP=y

# Bootloader Uyumluluğu (UF2 Koruması)
CONFIG_BOOTLOADER_MCUBOOT=y

# USB CDC ACM (Sanal Seri Port) Aktifleştirme
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
